
services:
  # Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: 5mkt-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: 5mktdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Mensageria RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 5mkt-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
